### ISSUE TITLE
configurator: update Node example

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/cloud-issues#20]
# Problem
The Node example on the last page of the configurator fails with: 

```
  const pipeline = new DeviceDetectionCloudPipelineBuilder({
                   ^

TypeError: DeviceDetectionCloudPipelineBuilder is not a constructor
    at run (/private/tmp/testnode/test.js:7:20)
    at Object.<anonymous> (/private/tmp/testnode/test.js:86:1)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47


```

# Fix
The only thing that needs to change in the code example is: 

`require('fiftyone.devicedetection')` should be replaced with `require('fiftyone.devicedetection.cloud')`

# Instructions how to get there

On the last step of the configurator wizard (to get there you have to check Free Product is enough for me, and agree that some properties will not be accessible and go to Implementation) there are (Server) instructions on the integration. Here are the instructions for Node:

NPM - DEVICE DETECTION
```sh
npm i fiftyone.devicedetection
```

NPM - GEO LOCATION
```sh
npm i fiftyone.geolocation
```

EXAMPLE NODE.JS CODE
```js
const path = require('path');
const DeviceDetectionCloudPipelineBuilder =
  require('fiftyone.devicedetection').DeviceDetectionCloudPipelineBuilder;
const run = async function (resourceKey, output) {
  // The pipeline should be managed as a singleton. Creating a pipeline instance for every request
  // will cause extreme resource problems.
  const pipeline = new DeviceDetectionCloudPipelineBuilder({
    resourceKey: resourceKey,
    // inhibit sharing usage for this test, usually this should be set 'true'.
    shareUsage: false
  }).build();
  // To monitor the pipeline we can put in listeners for various log events.
  // Valid types are info, debug, warn, error
  pipeline.on('error', console.error);
  // Get a flow data from the singleton pipeline for each detection
  const data = pipeline.createFlowData();
  // Add the evidence values to the flow data
  data.evidence.add(
    'header.user-agent',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ' +
    'AppleWebKit/537.36 (KHTML, like Gecko) ' +
    'Chrome/98.0.4758.102 Safari/537.36');
  data.evidence.add(
    'header.sec-ch-ua-mobile',
    '?0');
  data.evidence.add(
    'header.sec-ch-ua',
    '" Not A; Brand";v="99", "Chromium";v="98", ' +
    '"Google Chrome";v="98"');
  data.evidence.add(
    'header.sec-ch-ua-platform',
    '"Windows"');
  data.evidence.add(
    'header.sec-ch-ua-platform-version',
    '"14.0.0"');
  // Process the flow data.
  await data.process();
  // Get the results.
  const device = data.device;
  output.write(`device.IsMobile: ${device.ismobile.value}
`);
  output.write(`device.SetHeaderHardwareAccept-CH: ${device['setheaderhardwareaccept-ch'].value}
`);
  output.write(`device.SetHeaderBrowserAccept-CH: ${device['setheaderbrowseraccept-ch'].value}
`);
  output.write(`device.JavascriptGetHighEntropyValues: ${device.javascriptgethighentropyvalues.value}
`);
  output.write(`device.IsTablet: ${device.istablet.value}
`);
  output.write(`device.ScreenPixelsWidth: ${device.screenpixelswidth.value}
`);
  output.write(`device.ScreenPixelsWidthJavaScript: ${device.screenpixelswidthjavascript.value}
`);
  output.write(`device.ScreenPixelsHeight: ${device.screenpixelsheight.value}
`);
  output.write(`device.ScreenPixelsHeightJavaScript: ${device.screenpixelsheightjavascript.value}
`);
  output.write(`device.HardwareVendor: ${device.hardwarevendor.value}
`);
  output.write(`device.HardwareModel: ${device.hardwaremodel.value}
`);
  output.write(`device.HardwareName: ${device.hardwarename.value}
`);
  output.write(`device.DeviceType: ${device.devicetype.value}
`);
  output.write(`device.PlatformVendor: ${device.platformvendor.value}
`);
  output.write(`device.SetHeaderPlatformAccept-CH: ${device['setheaderplatformaccept-ch'].value}
`);
  output.write(`device.PlatformName: ${device.platformname.value}
`);
  output.write(`device.PlatformVersion: ${device.platformversion.value}
`);
  output.write(`device.BrowserVendor: ${device.browservendor.value}
`);
  output.write(`device.BrowserName: ${device.browsername.value}
`);
  output.write(`device.BrowserVersion: ${device.browserversion.value}
`);
  output.write(`device.IsCrawler: ${device.iscrawler.value}
`);
};

const args = process.argv.slice(2);
const resourceKey = "...";
run(resourceKey, process.stdout);

module.exports = {
  run: run
};
```

**Comment by justadreamer** [comment]
please check if this change has been deployed - I still see 'fiftyone.devicedetection' in the configurator example

**Comment by ben51degrees** [comment]
This is definitely live now. Presumably there was some pages cached if you had visited before.
Here's what I see:
```js
const path = require('path');
const DeviceDetectionCloudPipelineBuilder =
  require('fiftyone.devicedetection.cloud').DeviceDetectionCloudPipelineBuilder;
```
@justadreamer could you confirm you see this too after a full page refresh? Then we can close the issue.

**Comment by justadreamer** [comment]
caching indeed.  had to use Incognito browser to double check.  Thanks @ben51degrees can be closed now
